### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by jchoneandonly** [i3130002/Battery-Controller#1]
im a little new to linux and dont know how to install this program. would it be possible to add installation instructions on the readme or something?

**Comment by i3130002** [comment]
Hello, Surly

I'm glad that you are interested in this project. 

I'll add the installation to the `README.md` file

**Comment by i3130002** [comment]
Dear @jchoneandonly,

Hope you enjoy using this project. Let me know if you had issues.

With regards
